spring.application.name=CinemaBookingApp
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=cinema_booking_db
server.port = 8080
app.jwt.secret=${SECRETKEY}
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000
app.payStack.secret=${PAYSTACK_SECRETKEY}
app.allowedIps=52.214.14.220,52.49.173.169,52.31.139.75