
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port = ${PORT:8080}
app.jwt.secret=${SECRETKEY}
app.jwt.expiration=${JWT_EXPIRATION}
app.jwt.refresh-expiration=${JWT_REFRESH}
app.payStack.secret=${PAYSTACK_SECRETKEY}
spring.mail.host=smtp.resend.com
spring.mail.port=${RESEND_PORT}
spring.mail.username=resend
spring.mail.password=${RESEND_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true





